app/models.py
from app import db


class Query(db.Model):
    __tablename__ = 'query'
    # PLACEHOLDER DB CLASS
    id = db.Column(db.Integer, primary_key=True)
    product = db.Column(db.String)
    title = db.Column(db.String)
    date = db.Column(db.String)
    trading_name = db.Column(db.String)
    address = db.Column(db.String)
    latitude = db.Column(db.String)
    longitude = db.Column(db.String)
    brand = db.Column(db.String)

    def __repr__(self):
        return "Query id: {}\n Product: {}\nDate: {}".format(self.id,
                                                             self.product,
                                                             self.date)

app/__init__.py
# Imports
from flask import Flask
from config import config
from flask_sqlalchemy import SQLAlchemy
from fuelwatcher import FuelWatch
from flask_googlemaps import GoogleMaps
# Instantiations

db = SQLAlchemy()
fuelwatch = FuelWatch()
google_maps = GoogleMaps(key='AIzaSyDeKO22YmX_a5lsoeImXUkWx7d0H36k3sY')



def create_app(config_name):
    """Flask Application Factory."""
    # ------- Flask Setup
    app = Flask(__name__)
    # app.config.from_object(config['default'])
    app.config.from_object(config[config_name])

    # ------ Application Factory

    db.init_app(app)
    # google_maps.init_app(app)
    GoogleMaps(app)
    # with app.test_request_context():
    with app.app_context():
        """Creates context to drive the db.create_all()"""
        db.create_all()

    from .core import core as core
    app.register_blueprint(core)
    '''
    Blueprint was required after making the application factory.
    As the app instance is created and configured at runtime and thus the 'app'
    has already created, you cannot access the 'app' after this. 
    I.e. the app in app.route is inaccessible: blueprints mitigate this.
    '''

    return app

app/core/__init__.py
from flask import Blueprint

"""This creates the core blueprint. """
core = Blueprint('core', __name__)

from . import routes

app/core/routes.py
import logging
from . import core
from flask import render_template, jsonify, redirect, flash, abort, request, \
    url_for
from app import db, fuelwatch
from fuelwatcher import constants
from flask_googlemaps import Map  # remove once /test finished
from .utils import mapping
from app.models import *

logging.basicConfig(level=logging.INFO)

@core.route('/test')
def test():
    # creating a map in the view
    perth = Map(
        identifier="perth",
        lat=-31.0,
        lng=115.0,
    )
    mymap = Map(
        identifier="view-side",
        lat=37.4419,
        lng=-122.1419,
        markers=[(37.4419, -122.4419), (37.5, -122.4)]
    )
    sndmap = Map(
        identifier="sndmap",
        lat=37.4419,
        lng=-122.1419,
        markers=[
            {
                'icon': 'http://maps.google.com/mapfiles/ms/icons/green-dot.png',
                'lat': 37.4419,
                'lng': -122.1419,
                'infobox': "<b>Hello World</b>"
            },
            {
                'icon': 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
                'lat': 37.4300,
                'lng': -122.1400,
                'infobox': "<b>Hello World from other place</b>"
            }
        ]
    )
    return render_template('map.html', perth=perth, mymap=mymap, sndmap=sndmap)


@core.route('/')
def redirect_index():
    return redirect('index/today')


@core.route('/index/<day>', methods=['POST', 'GET'])
@core.route('/<day>', methods=['POST', 'GET'])
def index(day):
    """User initiated selection of day

    :arg day takes in options {today, yesterday, tomorrow}

    :return index.html with top ten prices for user selected :arg day
    """
    fuelwatch.query(product=1, day=day)
    ulp = fuelwatch.get_xml[:10]
    fuelwatch.query(product=2, day=day)
    p_ulp = fuelwatch.get_xml[:10]
    fuelwatch.query(product=4, day=day)
    dsl = fuelwatch.get_xml[:10]
    fuelwatch.query(product=5, day=day)
    lpg = fuelwatch.get_xml[:10]

    suburbs, product = constants.SUBURB, constants.PRODUCT

    return render_template('index.html', ulp=ulp, p_ulp=p_ulp, dsl=dsl,
                           lpg=lpg, day=day, suburbs=suburbs,
                           product=product)


@core.route('/regions')
def regions():
    regions = constants.REGION

    return render_template('regions.html', regions=regions)


@core.route('/regions/<region>/<product>')
def region(region, product):
    products = constants.PRODUCT
    if product is not None:
        fuelwatch.query(region=int(region), product=int(product))
    else:
        fuelwatch.query(region=int(region), product=product)

    resp = fuelwatch.get_xml
    region_value = constants.REGION.get(int(region))
    product_value = constants.PRODUCT.get(int(product))
    if not resp:
        flash(
            '{product} Not Found in {region}'.format(
                region=region_value, product=product_value))
        return redirect(url_for('core.region', region=region, product=1))
    region_map = mapping(resp)

    return render_template('region.html', region=region, resp=resp,
                           region_value=region_value,
                           region_map=region_map, products=products,
                           product=product, product_value=product_value)


@core.route('/search_results/', methods=['POST', 'GET'])
def search_results():
    product = request.form.get('fuel')
    suburb = request.form.get('suburb')
    product_key = [k for k, v in constants.PRODUCT.items() if v == product][0]
    fuelwatch.query(suburb=suburb, product=product_key)
    resp = fuelwatch.get_xml
    if not resp:
        flash('Sorry! {0} is not availabe in {1} Please try a new search'.
              format(product, suburb))
        return redirect('index/today')
    maps = mapping(resp)
    return render_template('result.html', resp=resp, suburb=suburb,
                           product=product_key, product_value=product,
                           maps=maps)


@core.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404


@core.errorhandler(500)
def internal_error(error):
    return render_template('500.html'), 500

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fuelwatcher | A West Australia FuelWatch Aggregator and Search
        Site.</title>
    <link rel="stylesheet" type="text/css" href="
            {{ url_for('static', filename='css/bulma.css') }}">
    <!--   <link rel="stylesheet"
             href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css"> -->
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='img/favicon.ico') }}">
    <script defer
            src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    {% block maps %}{% endblock %}
</head>

<body>

{% block navbar %}
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item"
               href="{{ url_for('core.index', day='today') }}">
                <p class="is-size-4 has-text-weight-bold">
                    FUELWATCHER
                </p>
            </a>
            <div class="navbar-burger" data-target="topstories-nav">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="topstories-nav" class="navbar-menu">
            <div class="navbar-start">
                <div class="navbar-start">
                    <a class="navbar-item has-text-white"
                       href="{{ url_for('core.regions') }}">
                        Regions
                    </a>
                </div>
            </div>
        </div>
    </nav>
{% endblock %}


<!-- Message Flashing -->
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="container is-fluid">
                <div class="notification is-warning has-text-centered is-size-3">
                    <button class="delete"></button>
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}


{% block content %}

{% endblock %}

{% block footer %}
    <footer class="footer">
        <div class="container is-fluid">
            <div class="content has-text-centered">
                <p>
                    <strong>Fuelwatcher</strong> by <a
                        href="https://danielms.site">Daniel
                    Michaels</a>. The source code is licensed
                    <a href="http://opensource.org/licenses/mit-license.php">MIT</a>.
                    The website content
                    is licensed <a
                        href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC
                    BY NC SA 4.0</a>.
                </p>
            </div>
        </div>
    </footer>
{% endblock %}

{% block scripts %}
    {% include 'scripts.html' %}
{% endblock %}
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}

    <form action="{{ url_for('core.search_results') }}" method="post">
        <div class="container is-fluid">
            <div class="notification">
                <p class="is-size-4 has-text-centered">Search</p>
                <div class="field has-addons">
                    <p class="control">
                    <span class="select">
                         <select name="fuel"> <!-- attr flask.request looks for -->
                             {% for fuel in product.values() %}
                                 <option>
                                {{ fuel }}
                                </option>
                             {% endfor %}
                    </select>
                </span>
                    </p>
                    <div class="select is-fullwidth">
                        <select name="suburb">
                            <!-- attr flask.request looks for -->
                            {% for suburb in suburbs %}
                                <option>{{ suburb }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <p class="control is-expanded">
                    </p>
                    <p class="control">
                        <input class="button is-info" type="submit"
                               value="Submit">
                        </input>
                    </p>
                </div>
            </div>
        </div>
    </form>
    <!-- end
    <!-- end drop down -->

    <section class="hero">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Fuelwatcher Western Australia
                </h1>
                <h2 class="subtitle">
                    <a href="{{ url_for('core.index', day='today') }}">Today</a>
                    /
                    <a href="{{ url_for('core.index', day='yesterday') }}">Yesterday</a>
                    /
                    <a href="{{ url_for('core.index', day='tomorrow') }}">Tomorrow</a>
                </h2>
            </div>
        </div>
    </section>
    <div class="container is-fluid">
        <div class="columns">
            <div class="column">
                <p class="notification is-size2 has-text-weight-bold has-text-centered">
                    Unleaded Petrol</p>
                {% for data in ulp %}
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                {{ data.title }}
                            </p>
                        </header>
                        <div class="card-content">
                            <div class="content">
                                <p>{{ data.description }}</p>
                            </div>
                        </div>
                    </div>
                    <br>
                {% else %}
                {% endfor %}
            </div>
            <div class="column">
                <p class="notification is-size2 has-text-weight-bold has-text-centered">
                    Premium Unleaded Petrol</p>
                {% for data in p_ulp %}
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                {{ data.title }}
                            </p>
                        </header>
                        <div class="card-content">
                            <div class="content">
                                <p>{{ data.description }}</p>
                            </div>
                        </div>
                    </div>
                    <br>

                {% else %}
                {% endfor %}
            </div>
            <div class="column">
                <p class="notification is-size2 has-text-weight-bold has-text-centered">
                    Diesel</p>
                {% for data in dsl %}
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                {{ data.title }}
                            </p>
                        </header>
                        <div class="card-content">
                            <div class="content">
                                <p>{{ data.description }}</p>
                            </div>
                        </div>
                    </div>
                    <br>

                {% else %}
                {% endfor %}
            </div>
            <div class="column">
                <p class="notification is-size2 has-text-weight-bold has-text-centered has-border">
                    LPG</p>
                {% for data in lpg %}
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                {{ data.title }}
                            </p>
                        </header>
                        <div class="card-content">
                            <div class="content">
                                <p>{{ data.description }}</p>
                            </div>
                        </div>
                    </div>
                    <br>

                {% else %}
                {% endfor %}
            </div>
        </div>
    </div>

</body>

{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

app/templates/map.html
{#{% extends 'base.html' %}#}

<!DOCTYPE html>
    <html>
    <head>
{#            {{"decoupled-map"|googlemap_js(37.4419, -122.1419, markers=[(37.4419, -122.1419)])}}#}
        {{ perth.js }}
            {{mymap.js}}
            {{sndmap.js}}
    </head>
    <body>
        <h1>Flask Google Maps Example</h1>

{#        <h2>daniel</h2>#}
{##}
{#        <h2> Template function centered, no marker </h2>#}
{#        {{googlemap("simple-map", 37.4419, -122.1419)}}#}
{##}
{#        <h2> Template filter decoupled with single marker </h2>#}
{#        {{"decoupled-map"|googlemap_html(-32.4419, 115.1419)}}#}
{##}
{#        <h2> Template function with multiple markers </h2>#}
{#        {% with map=googlemap_obj("another-map", 37.4419, -122.1419, markers=[(37.4419, -122.1419), (37.4300, -122.1400)]) %}#}
{#            {{map.html}}#}
{#            {{map.js}}#}
{#        {% endwith %}#}
        <h1>perth</h1>
        {{ perth.html }}

        <h2> First map generated in view</h2>
        {{mymap.html}}

        <h2> Second map generated in view</h2>
        <h3> Example for different icons in multiple markers with infoboxes</h3>
        {{sndmap.html}}

    </body>
</html>

app/templates/region.html
{% extends 'base.html' %}
{% block maps %}{{ region_map.js }}{% endblock %}

{% block content %}
    <div class="container is-fluid">
        <div class="columns">
            <div class="column is-one-third">
                <p id="fuel-selector"
                   class="notification is-size-3 has-text-weight-bold has-text-centered">
                    {{ region_value }} - {{ product_value }}</p>
                {% if products is not none %}
                    {% for key, value in products.items() %}
                        <a class="button"
                           href="{{ url_for('core.region', region=region, product=key) }}">
                            {{ value }}
                        </a>
                    {% endfor %}
                {% endif %}
                {% for data in resp %}
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                {{ data.title }}
                            </p>
                        </header>
                        <div class="card-content">
                            <div class="content">
                                <p>{{ data.address }}</p>
                                <p>{{ data.location | capitalize }}</p>
                                <p>{{ data.description }}</p>
                            </div>
                        </div>
                    </div>
                    <br>
                {% endfor %}
            </div>
            <div class="column is-two-thirds is-mobile">
                <p class="notification is-size-3 has-text-weight-bold has-text-centered">
                    MAP</p>
                {#                <div class="container is-fullscreen">#}
                {{ region_map.html }}
                {#                    </div>#}
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

app/templates/regions.html
{% extends 'base.html' %}

{% block content %}
    <div class="container is-fluid">
        <div class="columns">
            <div class="column is-one-third">
                <p class="notification is-size-3 has-text-weight-bold has-text-centered">
                    Regions</p>
                {#        {% for region in regions.values() %}#}
                {% for key, value in regions.items() %}
                    <ul>
                        <li>
                            <p class="is-size-5"><a href="{{ url_for('core.region',
                    region=key, product=1) }}">{{ value }}</a></p>
                        </li>
                    </ul>
                {% endfor %}
                </p>
            </div>
            <div class="column is-two-thirds">
                <p class="notification is-size-3 has-text-weight-bold has-text-centered">
                    MAP</p>
                <p class="is-size-1">INPUT MAP WITH ALL GEO OF REGION</p>
                {#                {{ region.html }}#}
            </div>

        </div>
    </div>
{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

app/templates/result.html
{% extends 'base.html' %}
{% block maps %}{{ maps.js }}{% endblock %}

{% block content %}
    {% if resp is not none %}
        <div class="container is-fluid">
            <div class="columns">
            <div class="column is-one-third">
                <p class="notification is-size-3 has-text-weight-bold has-text-centered">
                    {{ suburb }} - {{ product_value }}</p>
                {% for data in resp %}
                    <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">
                            {{ data.title }}
                        </p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>{{ data.address }}</p>
                            <p>{{ data.location | capitalize }}</p>
                            <p>{{ data.description }}</p>
                        </div>
                    </div>
                    </div>

                    <br>
                                 {% else %}
                {% endfor %}
        </div>
    {% endif %}
    <div class="column is-two-thirds">
             <p class="notification is-size-3 has-text-weight-bold has-text-centered">
                MAP</p>
    {{ maps.html }}
    </div>
{% endblock %}

{% block footer %}
{{ super() }}
{% endblock %}

app/templates/scripts.html
<script>

    document.addEventListener('DOMContentLoaded', function () {

        // Get all "navbar-burger" elements
        var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {

            // Add a click event on each of them
            $navbarBurgers.forEach(function ($el) {
                $el.addEventListener('click', function () {

                    // Get the target from the "data-target" attribute
                    var target = $el.dataset.target;
                    var $target = document.getElementById(target);

                    // Toggle the class on both the "navbar-burger" and the "navbar-menu"
                    $el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');

                });
            });
        }

    });

    var deleteButtons = document.getElementsByClassName('delete');

    for (var i = 0; i < deleteButtons.length; i++) {
        deleteButtons[i].addEventListener('click', dismiss);
    }

    function dismiss(e) {
        this.parentNode.classList.add('is-hidden');
    }

</script>